## Author:    Daniel Sperl
## Copyright: Copyright 2014 Gamua
## License:   Simplified BSD

require 'rake/testtask'
require 'fileutils'
require 'yard'

desc 'Run tests'
task :default => :test

Rake::TestTask.new do |t|
  t.libs << 'test'
  t.verbose = true
end

YARD::Rake::YardocTask.new do |t|
  t.options = ["--markup=markdown"] # optional
end

desc 'Remove all files generated by Yard'
task :clobber_yard do
  FileUtils.rm_rf('doc', :verbose=>true)
  FileUtils.rm_rf('.yardoc', :verbose=>true)
end